all:
	echo "?"
swap:
	mkdir -p dist
	g++ swap.cpp -o dist/swap -std=c++11
	echo ""
	./dist/swap
lambda:
	mkdir -p dist
	g++ lambda.cpp -o dist/lambda
	echo ""
	./dist/lambda
lambda11:
	mkdir -p dist
	g++ lambda11.cpp -o dist/lambda11 -std=c++11
	echo ""
	./dist/lambda11
